version: '3.9'

services:
    # NGINX container
    nginx:
        container_name: ${APP_NAME}-nginx
        build:
            context: .docker/prod/nginx
            dockerfile: Dockerfile
        restart: "always"
        ports:
            - 88:80
        volumes:
            - .:/var/www/${APP_NAME}
            - .docker/prod/nginx/logs:/var/log/nginx
        links:
            - php
        networks:
            - ${APP_NAME}-network

    # PHP FastCGI Process Manager container
    php:
        container_name: ${APP_NAME}-php
        build:
            context: .
            dockerfile: .docker/prod/php/Dockerfile
            args:
              - APP_ENV=${APP_ENV}
              - APP_NAME=${APP_NAME}
        restart: always
        volumes:
            - .:/var/www/${APP_NAME}
            - .docker/prod/php/php.ini:/usr/etc/php/php.ini
        networks:
            - ${APP_NAME}-network

networks:
  RMS-network:
      driver: bridge